"""add_sentiment_and_keywords

Revision ID: acce57a2dc8e
Revises: 3d1b015ace44
Create Date: 2026-01-07 05:00:01.782989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acce57a2dc8e'
down_revision: Union[str, Sequence[str], None] = '3d1b015ace44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('sentiment', sa.String(length=20), nullable=True))
    op.add_column('feedback', sa.Column('keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'keywords')
    op.drop_column('feedback', 'sentiment')
    # ### end Alembic commands ###
